"""Add unique constraint to role_requests

Revision ID: 1771d1769595
Revises: 7347088be763
Create Date: 2025-02-06 11:40:02.821821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1771d1769595'
down_revision = '7347088be763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_requests', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_role_request', ['user_id', 'requested_role'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_requests', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_role_request', type_='unique')

    # ### end Alembic commands ###
