"""Add RoleRequest, User updates

Revision ID: 62aefc76bfce
Revises: 7977202918d6
Create Date: 2025-01-30 14:15:17.864334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62aefc76bfce'
down_revision = '7977202918d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        # Added a name for the foreign key constraint
        batch_op.create_foreign_key('fk_role_requests_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_requests', schema=None) as batch_op:
        # Drop the foreign key constraint by name
        batch_op.drop_constraint('fk_role_requests_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
