"""update Tables Role ,User, RoleRequest

Revision ID: 7347088be763
Revises: 4f0acc8b239c
Create Date: 2025-01-30 16:42:40.007519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7347088be763'
down_revision = '4f0acc8b239c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_role_requests_role_id', 'role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_role_requests_role_id', type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
