"""Add RoleRequest, User Role updates

Revision ID: 7977202918d6
Revises: 7b3dbf77e6a4
Create Date: 2025-01-30 13:54:06.343722
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7977202918d6'
down_revision = '7b3dbf77e6a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_requests', schema=None) as batch_op:
        # Drop columns directly
        batch_op.drop_column('role_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_requests', schema=None) as batch_op:
        # Add the columns back
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), nullable=True))
        
        # Recreate the foreign key constraints
        batch_op.create_foreign_key('fk_role_requests_role_id', 'role', ['role_id'], ['id'])
        batch_op.create_foreign_key('fk_role_requests_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
